export default [
    {
        roomId: 'SUP_T',
        type: 'Superior Twin Room',
        adultNumber: 2,
        childNumber: 2,
        view: 'Ocean View',
        bed: '2 Single Beds',
        description: 'Standard Two Double Beds Non Smoking - Room Includes 2 Double Beds (about Full Size), Microwave and Mini-Refrigerator, as well as a 50 Flat Screen TV. Free Wi-Fi Throughout Property.',
        price: 100,
        imageUrl: require('../assets/media/room_photo/sm_ABC_room.jpg'),
        largeImage: require('../assets/media/room_photo/lg_ABC_room_1.jpg'),
        promotionType: 'Discount',
        promotion: 'Discount 8% per night',
        promotionValue: 0.08,
    },
    {
        roomId: 'SUP_S',
        type: 'Superior Single Room',
        adultNumber: 2,
        childNumber: 2,
        view: 'Sea View',
        bed: '1 Single Bed',
        description: 'Standard Two Double Beds Non Smoking - Room Includes 2 Double Beds (about Full Size), Microwave and Mini-Refrigerator, as well as a 50 Flat Screen TV. Free Wi-Fi Throughout Property.',
        price: 100,
        imageUrl: require('../assets/media/room_photo/sm_DB_room.jpg'),
        largeImage: require('../assets/media/room_photo/lg_DB_room_1.jpg'),
        promotionType: 'Discount',
        promotion: 'Discount 8% per night',
        promotionValue: 0.08,
    },
    {
        roomId: 'STD_T',
        type: 'Standard Twin Room',
        adultNumber: 2,
        childNumber: 2,
        view: 'Sea View',
        bed: '2 Single Beds',
        description: 'Standard Two Double Beds Non Smoking - Room Includes 2 Double Beds (about Full Size), Microwave and Mini-Refrigerator, as well as a 50 Flat Screen TV. Free Wi-Fi Throughout Property.',
        price: 100,
        imageUrl: require('../assets/media/room_photo/sm_DT_room.jpg'),
        largeImage: require('../assets/media/room_photo/lg_DT_room_1.jpg'),
        promotionType: 'Discount',
        promotion: 'Discount 8% per night',
        promotionValue: 0.08,
    },
    {
        roomId: 'STD_S',
        type: 'Standard Single Room',
        adultNumber: 2,
        childNumber: 2,
        view: 'City View',
        bed: '1 Single Bed',
        description: 'Standard Two Double Beds Non Smoking - Room Includes 2 Double Beds (about Full Size), Microwave and Mini-Refrigerator, as well as a 50 Flat Screen TV. Free Wi-Fi Throughout Property.',
        price: 100,
        imageUrl: require('../assets/media/room_photo/sm_STD_room.jpg'),
        largeImage: require('../assets/media/room_photo/lg_STD_room_1.jpg'),
        promotionType: 'Discount',
        promotion: 'Discount 8% per night',
        promotionValue: 0.08,
    },
    {
        roomId: 'DLX_T',
        type: 'Delux Twin Room',
        adultNumber: 2,
        childNumber: 2,
        view: 'Sea View',
        bed: '2 Single Beds',
        description: 'Standard Two Double Beds Non Smoking - Room Includes 2 Double Beds (about Full Size), Microwave and Mini-Refrigerator, as well as a 50 Flat Screen TV. Free Wi-Fi Throughout Property.',
        price: 100,
        imageUrl: require('../assets/media/room_photo/sm_ST_room.jpg'),
        largeImage: require('../assets/media/room_photo/lg_ST_room_1.jpg'),
        promotionType: 'Discount',
        promotion: 'Discount 8% per night',
        promotionValue: 0.08,
    },
    {
        roomId: 'DLX_D',
        type: 'Delux Double Room',
        adultNumber: 2,
        childNumber: 2,
        view: 'Ocean View',
        bed: '1 King Beds',
        description: 'Standard Two Double Beds Non Smoking - Room Includes 2 Double Beds (about Full Size), Microwave and Mini-Refrigerator, as well as a 50 Flat Screen TV. Free Wi-Fi Throughout Property.',
        price: 100,
        imageUrl: require('../assets/media/room_photo/sm_SD_room.jpg'),
        largeImage: require('../assets/media/room_photo/lg_ST_room_1.jpg'),
        promotionType: 'Discount',
        promotion: 'Discount 8% per night',
        promotionValue: 0.08,
    },
]